### ISSUE TITLE
No default value for accesslevel - warning in php 8.2

### ISSUE THREAD

**Issue by magnushasselquist** [Tazzios/cblistmodule#14]
Warning: Undefined property: stdClass::$accesslevel in /var/www/html/modules/mod_cblistmodule/helper.php on line 44

Deprecated: str_ireplace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in /var/www/html/modules/mod_cblistmodule/helper.php on line 252

Suggest to set as "whole world" where not already set, and also use "whole world" as default when adding a new field - or require user to set a value.

**Comment by Tazzios** [comment]
v3.2.0 released
