### ISSUE TITLE
Order by results in SQL error. (j!5 +CB 2.9.2 )

### ISSUE THREAD

**Issue by internet-conception** [Tazzios/cblistmodule#16]
hello,

On a fresh install (j!5 + CB 2.9.2) I got this message on a blank page while trying to show a simple userlist (have only one userlist)

**1064

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''')) ORDER BY formatname asc LIMIT 10' at line 1**

Something simple I guess...

Any help ? thanks, byebye

**Comment by Tazzios** [comment]
when i choose at 'Order by field' for 'formatname' I also get an error.
'onlinestatus', 'connections' have the same effect.
name, username and others seem to work. 

Maybe some thing in the database has changed.

**Comment by internet-conception** [comment]
I tried name and username but I got the same result. Also tried to change the sort order.
Your module seems very nice btw ;)

**Comment by Tazzios** [comment]
Did you got exactly the same error with 'formatname' in the error?
If so then you are changing it in the wrong place, it can be set in the cb list AND it can be overwritten in the module.

**Comment by internet-conception** [comment]
Ok it work ;)
I set the module to list default and change it in the cb list ;)
Thanks

**Comment by Tazzios** [comment]
Great, I will leave this item open as i still need the check why it is happening.

Error that i got was: ("Unknown column 'formatname' in 'order clause'")."

**Comment by Tazzios** [comment]
These fields are dynamic CB fields and are not in the database as column:
1. connections
2. onlinestatus
3. formatname
4. pm

So i need the filter these fields so that the user cannot select these ones.

**Comment by internet-conception** [comment]
Ok it's fine for me ;)

**Comment by Tazzios** [comment]
v3.2.0 released
