### ISSUE TITLE
Joomla 4

### ISSUE THREAD

**Issue by magnushasselquist** [Tazzios/cblistmodule#3]
Hi friend! ;)
Did you look into adjusting the module to be compatible with Joomla 4?
/Magnus

**Comment by Tazzios** [comment]
I will exchange some gaming time for programming. It is a long time that I looked at my Joomla extensions. :)

**Comment by Tazzios** [comment]
Did some testing and seems to work fine in J4. I will release the update later this week.

Could you delete [your old version](https://extensions.joomla.org/extension/extension-specific/community-builder-extensions/hq-cb-list-for-community-builder/) and give mine a rating? :)

**Comment by magnushasselquist** [comment]
I am shifting over to your version on my site and will remove/rate when done! Best regards!

**Comment by Tazzios** [comment]
checked and added in 3.0.3
