### ISSUE TITLE
Label instead of Value of checkbox field

### ISSUE THREAD

**Issue by magnushasselquist** [Tazzios/cblistmodule#4]
When displaying a checkbox field there is an option in CB to have a Label for each value. The Label probably should be displayed instead of Value, when displayed in the module.

![image](https://user-images.githubusercontent.com/5380854/153380430-52788cf0-6475-4afe-91f9-59e9be6b9485.png)

**Comment by magnushasselquist** [comment]
This is from table #__comprofiler_field_values:
![image](https://user-images.githubusercontent.com/5380854/153382115-fedfe276-dbea-4fec-97b9-dcfd3669a28e.png)

**Comment by magnushasselquist** [comment]
(and Label only when there is a Label, else title)

**Comment by Tazzios** [comment]
Not yet released but you can update the helper file to test it. Currently it shows all labels with a space as separator. I`m not yet sure if (and how) I make a template option for this.

**Comment by Tazzios** [comment]
> (and Label only when there is a Label, else title)

Oeps, did not do that one yet.

**Comment by Tazzios** [comment]
> > (and Label only when there is a Label, else title)
> 
> Oeps, did not do that one yet.

Fixed

**Comment by magnushasselquist** [comment]
Thanks! really quick! :)

**Comment by Tazzios** [comment]
fixed in 3.0.3
